### ISSUE TITLE
Support for metadata

### ISSUE THREAD

**Issue by 7AC** [docker-library/go-dockerlibrary#18]
`Manifest2822Entry` doesn't seem to support comments, i.e., parsing and modifying a manifest would lose comments. What do you think about adding a `Metadata` attribute that people can use to enter data/comments transparent to the build system?

**Comment by 7AC** [comment]
@wglambert we could implement it ourselves we just need some guidance on how to structure it in a way that makes sense to you as well. Would it be ok to have something like:

```
Metadata: <strings>
```

**Comment by tianon** [comment]
I'm really hesitant to add just a generic catch-all "comments" field; this
reminds me of some of the discussions that happened around annotations in
the OCI image specification.  Essentially, it's hard to plan for what users
might end up putting in this field, and we don't plan to use this (and
don't want our image maintainers to be adding random metadata which we not
only parse but persist in a parsing round-trip), and thus really wouldn't
be properly maintaining or testing such a feature were it to be contributed.

**Comment by 7AC** [comment]
Fair enough
